/**
 * Employee Presentation Mapper
 *
 * Pure functions converting canonical Employee DTOs into Presentation Models
 * and vice-versa.
 */

import type {
  EmployeeDto,
  CreateEmployeeRequest,
  UpdateEmployeeRequest,
} from '../backend/employee';
import type { EmployeePresentationModel } from '../presentation/employee.presentation';
import type { LocalizedString } from '../presentation/restaurant.presentation';
import type { MapperOptions } from './restaurant.mapper';
import {
  MOCK_LOCALIZATION_CATALOG,
  EMPLOYEE_STATUS_LABELS,
} from './localizationCatalog';

/**
 * Maps a Canonical Employee DTO into a Vue Presentation Model
 */
export function mapEmployeeToPresentation(
  dto: EmployeeDto,
  options: MapperOptions = { useMockCatalog: true }
): EmployeePresentationModel {
  const catalogEntry = options.useMockCatalog !== false
    ? MOCK_LOCALIZATION_CATALOG[dto.id]
    : undefined;

  const firstName: LocalizedString = catalogEntry?.first_name || {
    ar: dto.first_name,
    en: dto.first_name,
  };

  const lastName: LocalizedString = catalogEntry?.last_name || {
    ar: dto.last_name,
    en: dto.last_name,
  };

  const fullName: LocalizedString = {
    ar: `${firstName.ar} ${lastName.ar}`.trim(),
    en: `${firstName.en} ${lastName.en}`.trim(),
  };

  const positionName: LocalizedString | null = (dto.position_id || dto.position)
    ? (catalogEntry?.position_title || (dto.position ? { ar: dto.position.name, en: dto.position.name } : null))
    : null;

  const statusBadge = EMPLOYEE_STATUS_LABELS[dto.status] || {
    label: { ar: dto.status, en: dto.status },
    variant: 'default' as const,
  };

  return {
    id: dto.id,
    restaurant_id: dto.restaurant_id,
    employee_number: dto.employee_number,
    employee_code: dto.employee_number, // Backward compatibility alias
    first_name: firstName,
    last_name: lastName,
    full_name: fullName,
    raw_first_name: dto.first_name,
    raw_last_name: dto.last_name,
    email: dto.email,
    phone: dto.phone,
    hire_date: dto.hire_date,
    termination_date: dto.termination_date,
    status: dto.status,
    status_badge: statusBadge,
    position_id: dto.position_id,
    position_name: positionName,
    user_id: dto.user_id,
    created_at: dto.created_at,
    updated_at: dto.updated_at,
  };
}

/**
 * Maps Presentation Model inputs into CreateEmployeeRequest
 *
 * PROHIBITED IN REQUEST:
 * - `id`: generated by database
 * - `restaurant_id`: provided via route parameter `/api/restaurants/{restaurant}/employees`
 * - `created_at`, `updated_at`, `deleted_at`: managed by Eloquent
 */
export function mapToCreateEmployeeRequest(
  presentation: Partial<EmployeePresentationModel> & {
    raw_first_name?: string;
    raw_last_name?: string;
  }
): CreateEmployeeRequest {
  const firstName = presentation.raw_first_name || presentation.first_name?.en || presentation.first_name?.ar || '';
  const lastName = presentation.raw_last_name || presentation.last_name?.en || presentation.last_name?.ar || '';

  return {
    first_name: firstName,
    last_name: lastName,
    email: presentation.email || '',
    phone: presentation.phone || '',
    hire_date: presentation.hire_date || new Date().toISOString().split('T')[0],
    employee_number: presentation.employee_number || presentation.employee_code,
    status: presentation.status || 'active',
    user_id: presentation.user_id !== undefined ? presentation.user_id : null,
    position_id: presentation.position_id !== undefined ? presentation.position_id : null,
  };
}

/**
 * Maps Presentation Model inputs into UpdateEmployeeRequest
 *
 * PROHIBITED IN REQUEST:
 * - `id`: immutable
 * - `restaurant_id`: cannot change employee tenant via update endpoint
 * - `created_at`, `updated_at`, `deleted_at`: managed by Eloquent
 */
export function mapToUpdateEmployeeRequest(
  presentation: Partial<EmployeePresentationModel> & {
    raw_first_name?: string;
    raw_last_name?: string;
  }
): UpdateEmployeeRequest {
  const req: UpdateEmployeeRequest = {};

  if (presentation.raw_first_name || presentation.first_name) {
    req.first_name = presentation.raw_first_name || presentation.first_name?.en || presentation.first_name?.ar;
  }
  if (presentation.raw_last_name || presentation.last_name) {
    req.last_name = presentation.raw_last_name || presentation.last_name?.en || presentation.last_name?.ar;
  }
  if (presentation.email !== undefined) {
    req.email = presentation.email;
  }
  if (presentation.phone !== undefined) {
    req.phone = presentation.phone;
  }
  if (presentation.hire_date !== undefined) {
    req.hire_date = presentation.hire_date;
  }
  if (presentation.termination_date !== undefined) {
    req.termination_date = presentation.termination_date;
  }
  if (presentation.employee_number !== undefined || presentation.employee_code !== undefined) {
    req.employee_number = presentation.employee_number || presentation.employee_code;
  }
  if (presentation.status !== undefined) {
    req.status = presentation.status;
  }
  if (presentation.user_id !== undefined) {
    req.user_id = presentation.user_id;
  }
  if (presentation.position_id !== undefined) {
    req.position_id = presentation.position_id;
  }

  return req;
}
