/**
 * Canonical Laravel Restaurant DTO and Request Payloads
 *
 * Reflects the authoritative schema from Laravel REST API.
 * Endpoints:
 * - GET  /api/restaurants
 * - POST /api/restaurants
 * - GET  /api/restaurants/{restaurant}
 * - PUT  /api/restaurants/{restaurant}
 */

export type RestaurantStatus = 'active' | 'inactive' | 'suspended' | 'archived';

/**
 * Canonical Restaurant Entity (Wire-level Laravel Model)
 */
export interface RestaurantDto {
  id: string;
  name: string;
  slug: string;
  currency_code: string;
  status: RestaurantStatus;
  timezone: string;
  address: string | null;
  city: string | null;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

/**
 * Request payload for POST /api/restaurants
 *
 * Prohibited fields:
 * - `id`: generated by database
 * - `slug`: auto-generated by backend from name
 * - `created_at`, `updated_at`, `deleted_at`: managed by Eloquent
 */
export interface CreateRestaurantRequest {
  name: string;
  currency_code?: string;
  timezone?: string;
  city?: string | null;
  address?: string | null;
  status?: RestaurantStatus;
}

/**
 * Request payload for PUT /api/restaurants/{restaurant}
 *
 * Prohibited fields:
 * - `id`: immutable primary key
 * - `created_at`, `updated_at`, `deleted_at`: managed by Eloquent
 */
export interface UpdateRestaurantRequest {
  name?: string;
  currency_code?: string;
  timezone?: string;
  city?: string | null;
  address?: string | null;
  status?: RestaurantStatus;
}
